apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
  namespace: n8n-test
data:
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_PASSWORD: pswrd
  N8N_BASIC_AUTH_USER: root
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_DATABASE: "postgresdb"
  DB_POSTGRESDB_HOST: "postgres-service"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_USER: "postgres"
  DB_POSTGRESDB_PASSWORD: "admin123"

  