apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: n8n-test
  labels:
    app: postgresql
data:
  PGDATA: "/data/pgdata"
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin123