apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
  namespace: n8n-sts
data:
  # DB_TYPE: "postgresdb"
  # DB_POSTGRESDB_DATABASE: "postgresdb"
  # DB_POSTGRESDB_HOST: "postgres-service"
  # DB_POSTGRESDB_PORT: "5432"
  # DB_POSTGRESDB_USER: "postgres"
  # DB_POSTGRESDB_PASSWORD: "admin123"
  PG_DATA: "/data/pgdata"
  POSTGRES_DB: "postgresdb"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "admin123"

  